# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0002_auto_20180410_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
