# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0005_auto_20180410_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
