# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0012_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vikash',
        ),
        migrations.DeleteModel(
            name='Vikash1',
        ),
    ]
