# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0013_auto_20180411_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_gst', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=100)),
                ('client_phone', models.IntegerField(max_length=10)),
                ('client_id', models.CharField(max_length=50)),
                ('client_id_number', models.CharField(max_length=50)),
            ],
        ),
    ]
