# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0014_clientdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
    ]
