# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 21:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0015_auto_20180414_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 55, 20, 264938)),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='client_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
