# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0016_auto_20180420_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 56, 46, 570938))),
            ],
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 56, 46, 569938)),
        ),
        migrations.AddField(
            model_name='bills',
            name='client_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginModule.ClientDetail'),
        ),
    ]
