# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0017_auto_20180420_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.CharField(max_length=20)),
                ('rate', models.IntegerField(max_length=10)),
                ('volume', models.IntegerField(max_length=10)),
                ('last_updated_time', models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 59, 43, 568938))),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 59, 43, 567938)),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 2, 59, 43, 566938)),
        ),
        migrations.AddField(
            model_name='billdescriptions',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginModule.Bills'),
        ),
    ]
