# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0019_auto_20180420_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=50)),
                ('date_of_supply', models.DateField()),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_gstin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 4, 24, 25, 246000)),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 4, 24, 25, 247000)),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 4, 24, 25, 244000)),
        ),
    ]
