# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0020_auto_20180422_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetail',
            name='tax_amount',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='tax_type',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='total_amount_after_tax',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='total_amount_before_tax',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 23, 9, 769039)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 23, 9, 769039)),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 23, 9, 768039)),
        ),
    ]
