# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0021_auto_20180423_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 26, 14, 422560)),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 26, 14, 423560)),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 26, 14, 421560)),
        ),
        migrations.AlterField(
            model_name='supplierdetail',
            name='tax_amount',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierdetail',
            name='total_amount_after_tax',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierdetail',
            name='total_amount_before_tax',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
