# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0022_auto_20180426_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 29, 7, 642560)),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 29, 7, 643560)),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 29, 7, 640560)),
        ),
    ]
