# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0023_auto_20180426_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 32, 19, 101560)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='total_amount',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 32, 19, 103560)),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='rate',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='billsdescriptions',
            name='volume',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 3, 32, 19, 100560)),
        ),
    ]
